import { NextAuthProvider } from "./../components/Providers";
import { getServerSession } from "next-auth";
import { authOptions } from "./lib/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { LinksContextProvider } from "@/components/LinksContext";
// Import the 'Navbar' component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="flex flex-col items-stretch w-full">
        <LinksContextProvider>
          <NextAuthProvider>
            <Navbar />
            {children}
            <Footer />
          </NextAuthProvider>
        </LinksContextProvider>
      </body>
    </html>
  );
}
